const playlistActionType = {
    SET_PLAYLIST: 'SET_PLAYLIST',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    SET_AUDIO_VOLUME: 'SET_AUDIO_VOLUME',
    SET_PLAYING_AUDIO: 'SET_PLAYING_AUDIO',
    SET_PLAYING_AUDIO_TIME: 'SET_AUDIO_TIME',
    SET_PLAYING_AUDIO_DURATION: 'SET_PLAYING_AUDIO_DURATION',
    SET_TIME_TICK_INTERVAL: 'SET_TIME_TICK_INTERVAL',
    RESET_PLAYING_AUDIO_TIME: 'RESET_PLAYING_AUDIO_TIME',
    TOGGLE_PLAY: 'TOGGLE_PLAY',
};

export default playlistActionType;
